### PR TITLE
Data.List: Add a needed space to the document

### PR DESCRIPTION
**Pull request by aiya000**
minimum :dog2:

### CODE REVIEW

**Comment by aiya000** [comment]
> # Run reviewdog.
> reviewdog -reporter=github-pr-check
> reviewdog: status=401: The access token not provided. Get token from > > https://reviewdog.app/gh/vim-jp/vital.vim
> The command "if [[ "${RUN_LINT}" == "true" ]] ; then bash scripts/run-lint-on-ci.sh ; fi" exited with 1.

🐶 ❓

**Comment by ujihisa** [comment]
rerunning travis-ci. Does anybody know how to rerun appveyor's builds?

**Comment by tyru** [comment]
@aiya000 

> Writing coverage file .coverage_covimerage.
> coverage xml
> No data to report.
> Command exited with code 1

It should be related to #608, #609 .
Please rebase or merge master.

**Comment by aiya000** [comment]
CIs seems it has many pendings... ? :thinking:

**Comment by tyru** [comment]
:+1:

**Pull request merged**
