### PR TITLE
Proposal: Interface Extension of MD5

### PR DESCRIPTION
**Pull request by tsuyoshicho**
Currently MD5 has only sum (like md5sum).

However, there is a shortage of APIs to use as components.

Proposal:

* sum : return hash string
* digest : return hash bytes list (new, easy to use for other process)

and matrix

* x(str) : accept string data
* x_raw(bytes) : accept bytes list

after PRed this API support.

Thanks.

### CODE REVIEW

**Comment by tsuyoshicho** [comment]
> x(str) : accept string data
> x_raw(bytes) : accept bytes list

maybe type adaptive (type(a:data) is... check)

**Comment by ujihisa** [comment]
@nicwest what do you think of these new 3 APIs? (seeing `Maintainer: nicwest   <oss@nic-west.com>` line)

**Comment by ujihisa** [comment]
TODO: add tests if we are on the right path

**Comment by tsuyoshicho** [comment]
Add testcases and small bug fix

**Comment by nicwest** [comment]
looks good to me

**Comment by ujihisa** [comment]
thx!

https://ci.appveyor.com/project/vim-jp/vital-vim/builds/24175108/job/4wv2vg9c7f4kudn7 tests passed but covimrage failed for some reason. It doesn't seem to be because of this pull request, so it should be safe to merge.

**Pull request merged**
