### PR TITLE
Deprecate Lua.Prelude module

### PR DESCRIPTION
**Pull request by ujihisa**
I introduced this ages ago, but I haven't actively maintain it. Nobody besides vital core is using this. I'd like to remove this in the future. Let's deprecate this first, so that people can still use just by renaming, and we can get feedback from them if they exist.

### CODE REVIEW

**Comment by tyru** [comment]
:+1:

**Comment by ujihisa** [comment]
oh right I need an github approval from you.

**Comment by tyru** [comment]
@thinca @lambdalisue @mattn @rhysd @haya14busa  what do you think?

**Comment by tyru** [comment]
hmm, you should have waited for others for a while? :thinking_face:
Not only Lua.Prelude, someone may want to say deprecation of vital modules, and so on.
However, I thought you didn't need to hurry.

**Comment by ujihisa** [comment]
True. Good point is that users can still use this module just by renaming, but the renaming process will trigger feedback ;)

**Pull request merged**
