### PR TITLE
for #442

### PR DESCRIPTION
**Pull request by ujihisa**
check #442 for the discussion

### CODE REVIEW

**Comment by thinca** [comment]
Please rebase to master or merge master to include #444.

**Comment by thinca** [comment]
ping

**Comment by thinca** [comment]
@ujihisa ping

**Comment by ujihisa** [comment]
`rebase`ed and `push -f`ed

**Comment by thinca** [comment]
Thanks!

**Comment by ujihisa** [comment]
`!b`

**Pull request merged**
