### PR TITLE
Web.HTTP support HTTP/2

### PR DESCRIPTION
**Pull request by rbtnn**
https://github.com/vim-jp/vital.vim/issues/635

### CODE REVIEW

**Comment by mattn** [comment]
I prefer to be strictly. So
```
'^HTTP/[12]\.\d\s\+\(\d\+\)\s\+\
```

**Comment by rbtnn** [comment]
@mattn There are a case where HTTP/2's header does not contain `.`.  
Please see https://github.com/rhysd/wandbox-vim/issues/10#issuecomment-471178152

**Comment by rbtnn** [comment]
It might prefer to be `\(\d\|\d\.\d\)`  than `[0-9.]\+`.

**Comment by mattn** [comment]
I'm thinking illegal value must be error.

HTTP/0.0
HTTP/3
HTTP/999999999999999999

We should include rhysd's patch.

**Comment by rbtnn** [comment]
@mattn  I see. I'll include rhysd's patch.

**Pull request merged**
