### PR TITLE
fix: Data.String: nsplit work same as split()

### LINKED ISSUE #704: Vital.Data.String.nsplit() doesn't keep empty
I expect `keepempty` flag keeps empty strings in the list, but they are not kept.

i.e.

```vim
let s:V = vital#foo#new()
call s:V.load('Data.String')

echom json_encode(split('bar::', ':', 1))
echom json_encode(s:V.Data.String.nsplit('bar::', 10, ':', 1))
```

->

```
['bar', '', '']
['bar']
```

### PR DESCRIPTION
**Pull request by tsuyoshicho**
close #704

Refine `nsplit()` implement like `split()`.

### CODE REVIEW

**Comment by tsuyoshicho** [comment]
Add test later

**Comment by tsuyoshicho** [comment]
Mac test fails other reasons.

**Comment by ujihisa** [comment]
Cont'd to https://github.com/vim-jp/vital.vim/pull/708 for MacVim

**Comment by tsuyoshicho** [comment]
I'm OK.

**Pull request closed without merging**
