### PR TITLE
Web.URI: fix: URI.new_from_seq_string('foo bar: baz') was wrongly accepted

### PR DESCRIPTION
**Pull request by tyru**
via https://github.com/tyru/open-browser.vim/issues/96

### CODE REVIEW

**Comment by ujihisa** [comment]
:+1::sushi:

**Comment by tyru** [comment]
あざす！ 🍣 

\# Travis が不穏なエラーで終了している… >`carthage: A full installation of Xcode.app 8.3 is required to compile this software`

**Comment by tyru** [comment]
帰ったら rebase します #530

**Comment by tyru** [comment]
@ujihisa++ @raa0121++

**Pull request merged**
