### PR TITLE
Text.TOML: comply with v0.4.0

### PR DESCRIPTION
**Pull request by hattya**
This is the first step for v0.5.0.

Spec:
https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md
https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md

Changelog (what's changed):
https://github.com/toml-lang/toml/blob/master/CHANGELOG.md#050--2018-07-11

### CODE REVIEW

**Comment by thinca** [comment]
Great work 👍 

--- 
From [CHANGELOG.md from TOML spec](https://github.com/toml-lang/toml/blob/master/CHANGELOG.md):

> Newline is now defined as LF or CRLF.

Would you add a test for this?

**Comment by hattya** [comment]
Here you go.

**Comment by tyru** [comment]
Added links to top PR comment.

> Spec:
> https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md
> https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md

**Comment by tyru** [comment]
Added changelog (what's changed) too

**Pull request merged**
